### ISSUE TITLE
Large numbers of async checks cause timeout errors

### ISSUE THREAD

**Issue by wspear** [AlexMili/Reachable#9]
This may be more user error than an issue with Reachable but if it's not possible to fix internally it may be worth noting in the documentation.  When using asyncio to test a large number of urls (more than 6000. 50 and 100 worked for me) almost all of the results come back as ConnectTimeout errors, and some with ConnectionError status. I'm guessing this is due to some limitation in the network capacity of the OS or system hardware, but I haven't been able to track down any guidelines for safe caps on simultaneous connections.

**Comment by AlexMili** [comment]
Yes by sending too much requests you will hit the limit or your system/hardware. To bypass this problem there is a `TaskPool` class available. I updated the documentation and you should be able to follow steps there : https://github.com/AlexMili/Reachable?tab=readme-ov-file#handling-high-volumes-with-taskpool

**Comment by wspear** [comment]
I think that has it covered, thanks!
